import streamlit as st
import requests

API_BASE = "http://127.0.0.1:8000"

st.set_page_config(
    page_title="Customer Support Intelligence",
    layout="wide"
)

# -----------------------------
# Sidebar Navigation
# -----------------------------
st.sidebar.title("📊 Customer Support Intelligence")

page = st.sidebar.radio(
    "Navigate",
    [
        "Analyze Call",
        "Call History",
        "Analytics Dashboard",
        "System Overview"
    ]
)



# -----------------------------
# Page: Analyze Call
# -----------------------------
if page == "Analyze Call":
    st.title("🎧 Analyze Customer Support Call")
    st.write("Upload a customer support call and extract actionable insights.")

    uploaded_file = st.file_uploader(
        "Upload an audio file",
        type=["wav", "mp3", "m4a", "flac", "ogg"]
    )

    st.caption("Supported formats: WAV, MP3, M4A, FLAC, OGG")

    if uploaded_file:
        st.audio(uploaded_file)

        if st.button("Analyze Call"):
            with st.spinner("Analyzing call using AI..."):
                files = {
                    "file": (uploaded_file.name, uploaded_file, "audio/wav")
                }
                response = requests.post(
                    f"{API_BASE}/analyze-call",
                    files=files
                )

            if response.status_code != 200:
                st.error("Failed to analyze call")
            else:
                result = response.json()
                transcript = result["transcript"]
                insights = result["insights"]

                st.success("Analysis completed")

                # -----------------------------
                # Transcript
                # -----------------------------
                st.subheader("📝 Transcript")
                st.write(transcript)

                # -----------------------------
                # Insight Cards
                # -----------------------------
                st.subheader("🔍 Extracted Insights")

                col1, col2, col3 = st.columns(3)

                with col1:
                    st.metric(
                        "Sentiment",
                        insights["sentiment"].capitalize(),
                    )
                    st.metric(
                        "Urgency",
                        insights["urgency"].capitalize(),
                    )

                with col2:
                    st.metric(
                        "Issue Category",
                        insights["issue_category"].capitalize(),
                    )
                    st.metric(
                        "Agent Behavior",
                        insights["agent_behavior"].capitalize(),
                    )

                with col3:
                    outcome = insights["call_outcome"]
                    label = "Resolved" if outcome == "resolved" else "Unresolved"

                    st.metric(
                        "Call Outcome",
                        label,
                    )

                # -----------------------------
                # Insight Explanation
                # -----------------------------
                st.info(
                    "These insights are generated by combining speech-to-text "
                    "and large language models, with deterministic rules used "
                    "to infer call resolution."
                )


# -----------------------------
# Page: Call History
# -----------------------------
elif page == "Call History":
    st.title("🗂 Call History")
    st.write("Browse and explore previously analyzed customer support calls.")

    response = requests.get(f"{API_BASE}/calls")

    if response.status_code != 200:
        st.error("Failed to load call history")
    else:
        calls = response.json()

        if not calls:
            st.info("No calls analyzed yet.")
        else:
            # Convert to table-friendly format
            table_data = [
                {
                    "ID": call["id"],
                    "Issue": call["issue_category"].capitalize(),
                    "Sentiment": call["sentiment"].capitalize(),
                    "Urgency": call["urgency"].capitalize(),
                    "Outcome": call["call_outcome"].capitalize(),
                    "Timestamp": call["created_at"],
                }
                for call in calls
            ]

            st.dataframe(
                table_data,
                use_container_width=True
            )

            st.subheader("🔎 Filter Calls")

            sentiments = sorted(set(call["sentiment"] for call in calls))
            outcomes = sorted(set(call["call_outcome"] for call in calls))

            selected_sentiment = st.selectbox(
                "Filter by Sentiment",
                ["All"] + [s.capitalize() for s in sentiments]
            )

            selected_outcome = st.selectbox(
                "Filter by Outcome",
                ["All"] + [o.capitalize() for o in outcomes]
            )

            filtered_calls = calls

            if selected_sentiment != "All":
                filtered_calls = [
                    c for c in filtered_calls
                    if c["sentiment"].capitalize() == selected_sentiment
                ]

            if selected_outcome != "All":
                filtered_calls = [
                    c for c in filtered_calls
                    if c["call_outcome"].capitalize() == selected_outcome
                ]

            st.divider()
            st.subheader("📋 Filtered Results")

            for call in filtered_calls:
                with st.expander(
                    f"Call #{call['id']} | "
                    f"{call['issue_category'].capitalize()} | "
                    f"{call['call_outcome'].capitalize()}"
                ):
                    st.write("📝 Transcript")
                    st.write(call["transcript"])

                    st.write("🔍 Insights")
                    st.json({
                        "Sentiment": call["sentiment"],
                        "Urgency": call["urgency"],
                        "Agent Behavior": call["agent_behavior"],
                        "Outcome": call["call_outcome"],
                    })



# -----------------------------
# Page: Analytics Dashboard
# -----------------------------
elif page == "Analytics Dashboard":
    st.title("📈 Analytics Dashboard")
    st.write("High-level trends and actionable insights across all customer support calls.")

    response = requests.get(f"{API_BASE}/calls")

    if response.status_code != 200:
        st.error("Failed to load analytics data")
    else:
        calls = response.json()

        if not calls:
            st.info("No analytics available yet.")
        else:
            # -----------------------------
            # Aggregate Metrics
            # -----------------------------
            total_calls = len(calls)

            unresolved_calls = [
                c for c in calls if c["call_outcome"] == "unresolved"
            ]
            high_urgency_calls = [
                c for c in calls if c["urgency"] == "high"
            ]
            billing_issues = [
                c for c in calls if c["issue_category"] == "billing"
            ]

            col1, col2, col3 = st.columns(3)

            with col1:
                st.metric("Total Calls", total_calls)

            with col2:
                st.metric(
                    "Unresolved Calls",
                    len(unresolved_calls),
                    f"{round(len(unresolved_calls) / total_calls * 100, 1)}%"
                )

            with col3:
                st.metric(
                    "High Urgency Calls",
                    len(high_urgency_calls),
                    f"{round(len(high_urgency_calls) / total_calls * 100, 1)}%"
                )

            st.divider()

            # -----------------------------
            # Charts
            # -----------------------------
            st.subheader("📊 Distribution Overview")

            sentiment_counts = {}
            urgency_counts = {}
            outcome_counts = {}

            for c in calls:
                sentiment_counts[c["sentiment"]] = sentiment_counts.get(c["sentiment"], 0) + 1
                urgency_counts[c["urgency"]] = urgency_counts.get(c["urgency"], 0) + 1
                outcome_counts[c["call_outcome"]] = outcome_counts.get(c["call_outcome"], 0) + 1

            col4, col5, col6 = st.columns(3)

            with col4:
                st.subheader("Sentiment")
                st.bar_chart(sentiment_counts)

            with col5:
                st.subheader("Urgency")
                st.bar_chart(urgency_counts)

            with col6:
                st.subheader("Outcome")
                st.bar_chart(outcome_counts)

            st.divider()

            # -----------------------------
            # Actionable Insights
            # -----------------------------
            st.subheader("🧠 Key Insights")

            if high_urgency_calls and unresolved_calls:
                overlap = [
                    c for c in high_urgency_calls
                    if c["call_outcome"] == "unresolved"
                ]

                if overlap:
                    st.warning(
                        f"{len(overlap)} high-urgency calls remain unresolved. "
                        "This indicates potential service bottlenecks requiring immediate attention."
                    )

            if billing_issues:
                st.info(
                    f"Billing-related issues account for {len(billing_issues)} calls. "
                    "This may indicate systemic billing or payment workflow problems."
                )

            polite_unresolved = [
                c for c in unresolved_calls
                if c["agent_behavior"] == "polite"
            ]

            if polite_unresolved:
                st.info(
                    "Several unresolved calls involved polite agents, "
                    "suggesting that resolution failures may be process-related rather than behavioral."
                )

            st.success(
                "These insights are derived by combining AI-extracted signals "
                "with deterministic analysis logic."
            )


# -----------------------------
# Page: System Overview
# -----------------------------
elif page == "System Overview":
    st.title("ℹ️ System Overview")
    st.write("Architecture, AI pipeline, and technology stack.")



